### ISSUE TITLE
[FE] Milestone/Label 페이지 세부 기능들 추가

### ISSUE THREAD

**Issue by wjddnjswjd12** [swing-park/issue-tracker#56]
- [x] 어두운색, 밝은색 <label>태그 달아서 글씨눌러도 체크되도록
- [x]  추가하기, 수정하기 창에 레이블 띄우기
- [x]  설정한 색깔에 맞춰서 레이블 보여주기
- [x] Input 값에 따라서 +완료버튼 disabled 풀기
- [x] 수정하기 창 취소버튼 추가
